import type { ErrorCode } from './error_codes.js';
import { ERROR_CODES } from './error_codes.js';

export const ERROR_HTTP_MAP: Record<ErrorCode, number> = {
  [ERROR_CODES.UNAUTHENTICATED]: 401,
  [ERROR_CODES.ADMIN_ONLY]: 403,
  [ERROR_CODES.ONBOARDING_REQUIRED]: 403,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.INVALID_ENV]: 400,
  [ERROR_CODES.MISSING_PARAMETERS]: 400,
  [ERROR_CODES.MISSING_TEXT]: 400,
  [ERROR_CODES.INVALID_PAYLOAD]: 400,
  [ERROR_CODES.INVALID_TIME_RANGE]: 400,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.BOOKING_NOT_FOUND]: 404,
  [ERROR_CODES.CONVERSATION_NOT_FOUND]: 404,
  [ERROR_CODES.INVALID_BOOKING_TRANSITION]: 409,
  [ERROR_CODES.PROFILE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.SERVICE_DISABLED]: 503,
  [ERROR_CODES.WHATSAPP_SEND_FAILED]: 502,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.INVARIANT_FAILED]: 500,
} as const;

export function mapErrorToHttp(error: ErrorCode): number {
  return ERROR_HTTP_MAP[error] ?? 500;
}
